name: 'Release Version'
description: 'Cut release at ease'
inputs:
  token:
    required: true
  version:
    required: true
  project:
    default: ''
  strategy:
    default: ''
  release-date-format:
    default: 'DD.MM.YYYY'
runs:
  using: 'node12'
  main: 'dist/index.js'
