const payload = {
    after: '5a94305b9f7ac7801479fc56d7b6293c87b022c8',
    base_ref: null,
    before: 'e7f4c83b5800a65059888afc81b975db035848ee',
    commits: [
        {
            author: [Object],
            committer: [Object],
            distinct: true,
            id: '5a94305b9f7ac7801479fc56d7b6293c87b022c8',
            message: 'Patch 1',
            timestamp: '2021-07-14T19:59:51+02:00',
            tree_id: '153fd86521d4df086c226989701f094bd4a11f6b',
            url: 'https://github.com/zattoo/cactus/commit/5a94305b9f7ac7801479fc56d7b6293c87b022c8'
        }
    ],
    compare: 'https://github.com/zattoo/cactus/compare/e7f4c83b5800...5a94305b9f7a',
    created: false,
    deleted: false,
    enterprise: {
        avatar_url: 'https://avatars.githubusercontent.com/b/1246?v=4',
        created_at: '2019-11-07T12:19:25Z',
        description: null,
        html_url: 'https://github.com/enterprises/zattoo-europa',
        id: 1246,
        name: 'Zattoo Europa AG',
        node_id: 'MDEwOkVudGVycHJpc2UxMjQ2',
        slug: 'zattoo-europa',
        updated_at: '2021-05-03T22:53:23Z',
        website_url: null
    },
    forced: false,
    head_commit: {
        author: {
            email: 'bogdanplieshka@gmail.com',
            name: 'Bogdan Plieshka',
            username: 'gotbahn'
        },
        committer: {
            email: 'bogdanplieshka@gmail.com',
            name: 'Bogdan Plieshka',
            username: 'gotbahn'
        },
        distinct: true,
        id: '5a94305b9f7ac7801479fc56d7b6293c87b022c8',
        message: 'Patch 1',
        timestamp: '2021-07-14T19:59:51+02:00',
        tree_id: '153fd86521d4df086c226989701f094bd4a11f6b',
        url: 'https://github.com/zattoo/cactus/commit/5a94305b9f7ac7801479fc56d7b6293c87b022c8'
    },
    organization: {
        avatar_url: 'https://avatars.githubusercontent.com/u/3417958?v=4',
        description: '',
        events_url: 'https://api.github.com/orgs/zattoo/events',
        hooks_url: 'https://api.github.com/orgs/zattoo/hooks',
        id: 3417958,
        issues_url: 'https://api.github.com/orgs/zattoo/issues',
        login: 'zattoo',
        members_url: 'https://api.github.com/orgs/zattoo/members{/member}',
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjM0MTc5NTg=',
        public_members_url: 'https://api.github.com/orgs/zattoo/public_members{/member}',
        repos_url: 'https://api.github.com/orgs/zattoo/repos',
        url: 'https://api.github.com/orgs/zattoo'
    },
    pusher: {
        email: 'b.pleshka@gmail.com',
        name: 'gotbahn'
    },
    ref: 'refs/heads/main',
    repository: {
        archive_url: 'https://api.github.com/repos/zattoo/cactus/{archive_format}{/ref}',
        archived: false,
        assignees_url: 'https://api.github.com/repos/zattoo/cactus/assignees{/user}',
        blobs_url: 'https://api.github.com/repos/zattoo/cactus/git/blobs{/sha}',
        branches_url: 'https://api.github.com/repos/zattoo/cactus/branches{/branch}',
        clone_url: 'https://github.com/zattoo/cactus.git',
        collaborators_url: 'https://api.github.com/repos/zattoo/cactus/collaborators{/collaborator}',
        comments_url: 'https://api.github.com/repos/zattoo/cactus/comments{/number}',
        commits_url: 'https://api.github.com/repos/zattoo/cactus/commits{/sha}',
        compare_url: 'https://api.github.com/repos/zattoo/cactus/compare/{base}...{head}',
        contents_url: 'https://api.github.com/repos/zattoo/cactus/contents/{+path}',
        contributors_url: 'https://api.github.com/repos/zattoo/cactus/contributors',
        created_at: 1626178535,
        default_branch: 'main',
        deployments_url: 'https://api.github.com/repos/zattoo/cactus/deployments',
        description: 'Cactus Release Cycle prototype',
        disabled: false,
        downloads_url: 'https://api.github.com/repos/zattoo/cactus/downloads',
        events_url: 'https://api.github.com/repos/zattoo/cactus/events',
        fork: false,
        forks: 0,
        forks_count: 0,
        forks_url: 'https://api.github.com/repos/zattoo/cactus/forks',
        full_name: 'zattoo/cactus',
        git_commits_url: 'https://api.github.com/repos/zattoo/cactus/git/commits{/sha}',
        git_refs_url: 'https://api.github.com/repos/zattoo/cactus/git/refs{/sha}',
        git_tags_url: 'https://api.github.com/repos/zattoo/cactus/git/tags{/sha}',
        git_url: 'git://github.com/zattoo/cactus.git',
        has_downloads: true,
        has_issues: true,
        has_pages: false,
        has_projects: true,
        has_wiki: true,
        homepage: null,
        hooks_url: 'https://api.github.com/repos/zattoo/cactus/hooks',
        html_url: 'https://github.com/zattoo/cactus',
        id: 385592614,
        issue_comment_url: 'https://api.github.com/repos/zattoo/cactus/issues/comments{/number}',
        issue_events_url: 'https://api.github.com/repos/zattoo/cactus/issues/events{/number}',
        issues_url: 'https://api.github.com/repos/zattoo/cactus/issues{/number}',
        keys_url: 'https://api.github.com/repos/zattoo/cactus/keys{/key_id}',
        labels_url: 'https://api.github.com/repos/zattoo/cactus/labels{/name}',
        language: 'JavaScript',
        languages_url: 'https://api.github.com/repos/zattoo/cactus/languages',
        license: null,
        master_branch: 'main',
        merges_url: 'https://api.github.com/repos/zattoo/cactus/merges',
        milestones_url: 'https://api.github.com/repos/zattoo/cactus/milestones{/number}',
        mirror_url: null,
        name: 'cactus',
        node_id: 'MDEwOlJlcG9zaXRvcnkzODU1OTI2MTQ=',
        notifications_url: 'https://api.github.com/repos/zattoo/cactus/notifications{?since,all,participating}',
        open_issues: 0,
        open_issues_count: 0,
        organization: 'zattoo',
        owner: {
            avatar_url: 'https://avatars.githubusercontent.com/u/3417958?v=4',
            email: 'support@zattoo.com',
            events_url: 'https://api.github.com/users/zattoo/events{/privacy}',
            followers_url: 'https://api.github.com/users/zattoo/followers',
            following_url: 'https://api.github.com/users/zattoo/following{/other_user}',
            gists_url: 'https://api.github.com/users/zattoo/gists{/gist_id}',
            gravatar_id: '',
            html_url: 'https://github.com/zattoo',
            id: 3417958,
            login: 'zattoo',
            name: 'zattoo',
            node_id: 'MDEyOk9yZ2FuaXphdGlvbjM0MTc5NTg=',
            organizations_url: 'https://api.github.com/users/zattoo/orgs',
            received_events_url: 'https://api.github.com/users/zattoo/received_events',
            repos_url: 'https://api.github.com/users/zattoo/repos',
            site_admin: false,
            starred_url: 'https://api.github.com/users/zattoo/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/zattoo/subscriptions',
            type: 'Organization',
            url: 'https://api.github.com/users/zattoo'
        },
        private: true,
        pulls_url: 'https://api.github.com/repos/zattoo/cactus/pulls{/number}',
        pushed_at: 1626285595,
        releases_url: 'https://api.github.com/repos/zattoo/cactus/releases{/id}',
        size: 190318,
        ssh_url: 'git@github.com:zattoo/cactus.git',
        stargazers: 0,
        stargazers_count: 0,
        stargazers_url: 'https://api.github.com/repos/zattoo/cactus/stargazers',
        statuses_url: 'https://api.github.com/repos/zattoo/cactus/statuses/{sha}',
        subscribers_url: 'https://api.github.com/repos/zattoo/cactus/subscribers',
        subscription_url: 'https://api.github.com/repos/zattoo/cactus/subscription',
        svn_url: 'https://github.com/zattoo/cactus',
        tags_url: 'https://api.github.com/repos/zattoo/cactus/tags',
        teams_url: 'https://api.github.com/repos/zattoo/cactus/teams',
        trees_url: 'https://api.github.com/repos/zattoo/cactus/git/trees{/sha}',
        updated_at: '2021-07-14T17:53:17Z',
        url: 'https://github.com/zattoo/cactus',
        watchers: 0,
        watchers_count: 0
    },
    sender: {
        avatar_url: 'https://avatars.githubusercontent.com/u/2461970?v=4',
        events_url: 'https://api.github.com/users/gotbahn/events{/privacy}',
        followers_url: 'https://api.github.com/users/gotbahn/followers',
        following_url: 'https://api.github.com/users/gotbahn/following{/other_user}',
        gists_url: 'https://api.github.com/users/gotbahn/gists{/gist_id}',
        gravatar_id: '',
        html_url: 'https://github.com/gotbahn',
        id: 2461970,
        login: 'gotbahn',
        node_id: 'MDQ6VXNlcjI0NjE5NzA=',
        organizations_url: 'https://api.github.com/users/gotbahn/orgs',
        received_events_url: 'https://api.github.com/users/gotbahn/received_events',
        repos_url: 'https://api.github.com/users/gotbahn/repos',
        site_admin: false,
        starred_url: 'https://api.github.com/users/gotbahn/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/gotbahn/subscriptions',
        type: 'User',
        url: 'https://api.github.com/users/gotbahn'
    }
};
