name: Release Version

on:
  # manually dispatched from Actions tab with Run Workflow
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
jobs:
  release-version:
    name: Release Version
    runs-on: ubuntu-latest
    steps:
      - name: Release Version
        uses: ./ # Uses an action in the root directory
        with:
          token: ${{github.token}}
          version: ${{github.event.inputs.version}}
          project: ''
          production: 'v1'
