name: Test
on: [pull_request]

jobs:
  lint:
    name: Statics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  changelog:
    name: Changelog
    if: contains(github.head_ref, 'dependabot') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/changelog@v1
        with:
          token: ${{github.token}}
